services:
  pg:
    image: postgres:15
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=rafaella.lopes
      - POSTGRES_PASSWORD=Location!
      - POSTGRES_DB=location
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
      image: redis
#      container_name: bff-shim-redis
      ports:
        - 6380:6379


    #  app:
    #    build: .
    #    ports:
    #      - "8080:8080"
    #    depends_on:
    #      - pg

volumes:
  pgdata: